[project]
name = "duui-gnfinder-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "uvicorn>=0.34.2",
]
